# ============================================================
# setup_env.ps1 — Interactive Supabase .env setup
# Run: powershell -ExecutionPolicy Bypass -File setup_env.ps1
# ============================================================

Write-Host ""
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "  1Fi Marketplace — Supabase .env Setup" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "You need two URLs from Supabase Dashboard:" -ForegroundColor Yellow
Write-Host "  Go to: supabase.com → Your Project → Settings → Database → Connection String" -ForegroundColor Yellow
Write-Host ""
Write-Host "  1. Transaction pooler (port 6543) → DATABASE_URL" -ForegroundColor Green
Write-Host "  2. Session pooler  OR Direct (port 5432) → DIRECT_URL" -ForegroundColor Green
Write-Host ""

$db  = Read-Host "Paste DATABASE_URL (Transaction pooler, port 6543)"
$dir = Read-Host "Paste DIRECT_URL   (Session pooler or Direct, port 5432)"
$port = Read-Host "Backend PORT [press Enter for 3000]"
if ([string]::IsNullOrWhiteSpace($port)) { $port = "3000" }

$envContent = @"
# 1Fi Marketplace Backend — Environment Variables
# Generated by setup_env.ps1 — DO NOT COMMIT THIS FILE

# Supabase PostgreSQL — Transaction pooler (for runtime queries)
DATABASE_URL="$db"

# Supabase PostgreSQL — Direct connection (for migrations/seeds)
DIRECT_URL="$dir"

# Express server port
PORT=$port

# Node environment
NODE_ENV="development"
"@

$envContent | Set-Content -Path "$PSScriptRoot\.env" -Encoding UTF8
Write-Host ""
Write-Host "✅ .env created at backend\.env" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. npm run db:generate    # generate Prisma client" -ForegroundColor White
Write-Host "  2. npm run db:push        # push schema to Supabase" -ForegroundColor White
Write-Host "  3. npm run db:seed        # seed demo products" -ForegroundColor White
Write-Host "  4. npm run dev            # start the API server" -ForegroundColor White
Write-Host ""
