# ============================================================
# setup_env.ps1 — One-time Supabase .env setup for 1Fi backend
# Run: powershell -ExecutionPolicy Bypass -File setup_env.ps1
# ============================================================

Write-Host ""
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "  1Fi Marketplace — Supabase Setup Wizard" -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "STEP 1: Get your Supabase connection strings" -ForegroundColor Yellow
Write-Host "  1. Go to https://supabase.com → Your Project"
Write-Host "  2. Click 'Connect' (top bar) or go to Settings → Database"
Write-Host "  3. Under 'Connection string' choose 'URI'"
Write-Host "  4. Copy the two URLs below:"
Write-Host ""
Write-Host "  Transaction pooler  (port 6543) → DATABASE_URL" -ForegroundColor Green
Write-Host "  Session pooler      (port 5432) → DIRECT_URL" -ForegroundColor Green
Write-Host ""

$dbUrl   = Read-Host "Paste DATABASE_URL  (port 6543 / Transaction pooler)"
$dirUrl  = Read-Host "Paste DIRECT_URL    (port 5432 / Session pooler or Direct)"

if ([string]::IsNullOrWhiteSpace($dbUrl) -or [string]::IsNullOrWhiteSpace($dirUrl)) {
    Write-Host "`n[ERROR] Both URLs are required." -ForegroundColor Red
    exit 1
}

$port = Read-Host "Backend PORT (press Enter for 3000)"
if ([string]::IsNullOrWhiteSpace($port)) { $port = "3000" }

# Write .env
@"
# 1Fi Marketplace Backend — auto-generated by setup_env.ps1
# DO NOT COMMIT THIS FILE

DATABASE_URL="$dbUrl"
DIRECT_URL="$dirUrl"
PORT=$port
NODE_ENV="development"
"@ | Set-Content "$PSScriptRoot\.env" -Encoding UTF8

Write-Host "`n[OK] .env created" -ForegroundColor Green
Write-Host ""
Write-Host "STEP 2: Install dependencies..." -ForegroundColor Yellow
Set-Location $PSScriptRoot
npm install

Write-Host ""
Write-Host "STEP 3: Generate Prisma client..." -ForegroundColor Yellow
npx prisma generate

Write-Host ""
Write-Host "STEP 4: Push schema to Supabase..." -ForegroundColor Yellow
npx prisma db push

Write-Host ""
Write-Host "STEP 5: Seed demo products..." -ForegroundColor Yellow
node prisma/seed.js

Write-Host ""
Write-Host "=============================================" -ForegroundColor Green
Write-Host "  Setup complete! Backend is ready." -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Green
Write-Host ""
Write-Host "Start the server:" -ForegroundColor Cyan
Write-Host "  npm run dev        (development — auto-restart)"
Write-Host "  npm start          (production)"
Write-Host ""
Write-Host "Then in Flutter, run:" -ForegroundColor Cyan
Write-Host "  flutter run --dart-define=USE_MOCK=false --dart-define=API_BASE_URL=http://localhost:3000"
Write-Host ""
